### ISSUE TITLE
Issue: keybinding for talent tab problem

### ISSUE THREAD

**Issue by class2u** [p3lim-wow/Talentless#1]
- What version are you using?
  70000.6-Release
- Can the issue be reproduced, and if so, how?
1. Set a keybinding for talent tab.
2. Press the key.

The result is specialization tab opened instead of talent tab if I have not opened  talent tab before.

**Comment by p3lim** [comment]
Was this using the keybindings provided with Talentless (found under "AddOns" in the keybinding interface)?

**Comment by class2u** [comment]
Yes, under "AddOns" in the keybinding interface.

**Comment by p3lim** [comment]
I can't seem to replicate this issue.
