### ISSUE TITLE
Tome of the...

### ISSUE THREAD

**Issue by Nico18151** [p3lim-wow/Talentless#3]
Hello, currently in the object to change talents outside a rest area, is using the [Tome of the Tranquil Mind](https://www.wowhead.com/item=141446/tome-of-the-tranquil-mind) this object is Legion, since currently the professions are dosed by expansion I think it would be a good idea to replace it with the one of BFA, [Tome of the Quiet Mind
](https://www.wowhead.com/item=153647/tome-of-the-quiet-mind#english) is much more useful for all the inscriptores that we created said volumes, since we have to look for them at the moment in the stock exchange and the addon ceases to be useful. Regards! :)

**Comment by p3lim** [comment]
I'll take a look at this next week, bit busy at the moment.
