### ISSUE TITLE
Feature Request: Heart of Azeroth Profiles

### ISSUE THREAD

**Issue by malikoth** [p3lim-wow/Talentless#4]
When I have different talent sets, one for questing, one for M+ dungeons, one for raiding, one for PvP, etc., I click the button for the right talent set, and then open up my Heart of Azeroth UI and manually set my active and passive abilities.  I'd love for Talentless to remember and set HoA abilities in addition to talents.

I wouldn't be surprised if you decline this feature request, because Talentless very clearly deals with talents, and I'm asking you to deal with something other than talents.  This might also be a bad idea, because HoA abilities are (presumably) only going to be a thing for BfA, so this request would be of time-limited value.  Still, if it didn't require a ton of extra time to implement, it might still be worth adding, and then removing when we move on to the next expansion pack.

If you're OK with the thought of adding this functionality, but don't care to implement it yourself, let me know and I'll look into submitting a PR myself.  (Haven't actually looked at your source code to see how hard it would be to figure out and extend)

**Comment by p3lim** [comment]
This is better suited for a separate addon (call it Heartless if you'd like), but I don't play the game any more and as such don't attempt to improve existing addons or create new ones, just maintain the ones I already have.
