### ISSUE TITLE
hello,i'm want give some advice,but not good at english.

### ISSUE THREAD

**Issue by teslagao** [p3lim-wow/Talentless#6]
Thanks for your hard work,today i update your addon "talentless 90000.18",found a little point get worser than 80000.17,that is The default interface is specialization interface，i can't set a shortcuts like old version to Directly open the  Talent interface ，thanks。

**Comment by p3lim** [comment]
Intentional change, the binds to open specific tabs were blocking the talent frame from showing in multiple scenarios, so it was removed. See the changelog.
